on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: build-stage
       run: echo "This steps build your image..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: test-stage
      run: echo "This step will test your app..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: deploy-stage
      run: echo "This step will deploy your app..."
